server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DevCodeStack/Eatza-App-Config/
          clone-on-start: true
          default-label: master
          search-paths:
          - '{application}'

    
    